version: "3.9"

services:
  backend:
    build: ./backend
    container_name: flask-backend
    ports:
      - "5000:5000"

  frontend:
    build: ./frontend
    container_name: vue-frontend
    ports:
      - "5173:80"
    depends_on:
      - backend
